---
title: "Simple document"
output: github_document
---

```{r,echo = FALSE, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

##IMPORT SOME DATA

I want to import 'FAS_litters.csv'

```{r}
litters_df = read_csv("data/FAS_litters.csv")#use "Tab" to get all the file name
```

Tay! i imported the data set. mow I want better names

```{r}
names(litters_df)

litters_df = janitor::clean_names(litters_df)
```

now I have better names. Let's look at the dataset

```{r}
litters_df

head(litters_df)
tail(litters_df)
```

view inside rmarkdown the document

```{r, eval= FALSE}
view(litters_df)
```

Here's skimr:

```{r}
skimr::skim(litters_df)
```


##Arguments in 'read_csv'

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 5,
    col_names = FALSE,
    na = "Low8")
litters_df
```

##parsing columns



##Reading from Excel

reading mlb data

```{r}
mlb11_df = read_excel("data/mlb11.xlsx")
```

```{r}
fellow_df = read_excel("data/LotR_Words.xlsx", range = "B3:D6")
```

##read sas file

```{r, eval = FALSE}
pulse_df = read_sas("data/public_pulse_data.sas7bdat")
```

